# Generated by Django 5.0 on 2023-12-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Em',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Em_name', models.CharField(max_length=100)),
                ('Em_id', models.CharField(max_length=100)),
                ('Em_salary', models.CharField(max_length=100)),
            ],
        ),
    ]
